---
version: "3"
services:
  influxdb:
    image: "influxdb:latest"
    networks:
    - "monitoring"
    ports:
    - 8086:8086
    volumes:
    - "./db:/var/lib/influxdb"

  influxdb-init:
    build: "docker/influxdb-init/"
    image: "influxdb-init:latest"
    networks:
    - "monitoring"
    depends_on:
    - "influxdb"
    command: curl -XPOST http://localhost:8086 --data-urlencode "q=CREATE DATABASE sensu"

  grafana:
    image: "grafana/grafana:latest"
    networks:
    - "monitoring"
    ports:
    - 4000:3000
    volumes:
    - "$PWD/files/grafana/provisioning/datasources/influxdb.yaml:/etc/grafana/provisioning/datasources/influxdb.yaml"

  sensu-backend:
    image: "sensu/sensu:2.0.0-beta.3.1"
    networks:
    - "monitoring"
    ports:
    - 3000:3000
    - 8080:8080
    - 8081:8081
    labels:
    - "io.sensu.description: The Sensu 2.0 backend"
    - "io.sensu.version: 2.0.0-beta.3.1"
    - "io.sensu.role: backend"
    command: "sensu-backend start"

  sensu-asset-server:
    image: "nginx:latest"
    networks:
    - "monitoring"
    ports:
    - 8000:80
    volumes:
    - "$PWD/files/nginx/nginx.conf:/etc/nginx/nginx.conf"
    - "$PWD/assets:/usr/share/nginx/html"

networks:
  monitoring:
    driver: "bridge"
