---
version: "3"
services:
  influxdb:
    image: "influxdb:latest"
    networks:
    - "monitoring"
    ports:
    - 8086:8086
    volumes:
    - "./data/influxdb:/var/lib/influxdb"
    - "./files/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf"

  influxdb-init:
    build:
      context: "docker/influxdb-init/"
    image: "influxdb-init:latest"
    networks:
    - "monitoring"
    depends_on:
    - "influxdb"
    command: "curl -XPOST http://influxdb:8086 --data-urlencode 'q=CREATE DATABASE sensu'"

  grafana:
    image: "grafana/grafana:latest"
    networks:
    - "monitoring"
    ports:
    - 4000:3000
    volumes:
    - "$PWD/files/grafana/provisioning/datasources/influxdb.yaml:/etc/grafana/provisioning/datasources/influxdb.yaml"

  sensu-backend:
    build:
      context: "docker/sensu-backend/"
    image: "sensu-backend:latest"
    networks:
    - "monitoring"
    ports:
    - 3000:3000
    - 8080:8080
    - 8081:8081
    volumes:
    - "./data/sensu/etcd:/var/lib/sensu/etcd"
    labels:
    - "io.sensu.description: The Sensu 2.0 backend"
    - "io.sensu.version: 2.0.0-beta.4.1"
    - "io.sensu.role: backend"
    command: "sensu-backend start --log-level debug"

  sensu-asset-server:
    image: "nginx:latest"
    networks:
    - "monitoring"
    ports:
    - 8000:80
    volumes:
    - "$PWD/files/nginx/nginx.conf:/etc/nginx/nginx.conf"
    - "$PWD/assets:/usr/share/nginx/html/assets"

  sensu-agent:
    image: "sensu/sensu:2.0.0-beta.4.1"
    networks:
    - "monitoring"
    volumes:
    - "$PWD/config/agent.yml:/etc/sensu/agent.yml"
    depends_on:
    - "sensu-backend"
    labels:
    - "io.sensu.description: The Sensu 2.0 agent"
    - "io.sensu.version: 2.0.0-beta.4.1"
    - "io.sensu.role: agent"
    command: "sensu-agent start --backend-url ws://sensu-backend:8081 --log-level debug"

networks:
  monitoring:
    driver: "bridge"
